apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-exporter-podmonitor
  labels:
    team: insightops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  namespaceSelector:
    matchNames:
      - observability
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
