prometheus:
  alertmanager:
    enabled: false
  server:
    enabled: true
    persistentVolume:
      enabled: false      
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  server:
    retention: "7d"
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

loki:
  persistence:
    enabled: false
  # config: |
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      pipeline_stages:
        - cri: {}
      extraScrapeConfigs: |
        - job_name: kubernetes-pods
          static_configs:
            - targets: ['localhost']
              labels:
                job: varlogs
                __path__: /var/log/pods/*/*/*.log
